//DIFFERENT TYPE OF ACESS MODIFIERS FOR TESTING10
public class SAMPLE				//USER DEFINED METHOD
{
	private int a=100;			//PRIVATE VARIABLE
	int b=200;					//DEFAULT VARIABLE
	protected int c=300;		//PROTECTED VARRIABLE
	public int d=400;			//PUBLIC VARIABLE
}